@startuml Figure 11-1
rectangle "Policy Layer" as policy
rectangle "Mechanism Layer" as mech
rectangle "Utility Layer" as util
policy ..> mech
mech ..> util
@enduml

@startuml Figure 11-2
package Policy{
rectangle "Policy Layer" as policy
rectangle "Policy Service Interface" <<interface>> as polInt
}

package Mechanism{
rectangle "Mechanism Layer" as mech
rectangle "Mechanism Service Interface" <<interface>> as mechInt
}

package Utility{
rectangle "Utility Layer" as ult
}

policy -r-> polInt
mech .u.|> polInt
mech -r-> mechInt
ult .u.|> mechInt

@enduml

@startuml Figure 11-3
class Button {
    Poll()
}

class Lamp {
    TurnOn()
    TurnOff()
}

Button -> Lamp
@enduml

@startuml Figure 11-4
class Button {
    Poll()
}

interface ButtonServer <<interface>> {
    TurnOn()
    TurnOff()
}

class Lamp

Button -> ButtonServer

Lamp -u-|> ButtonServer
@enduml

@startuml Figure 11-5
interface Regulate <<function>>

interface Thermometer <<interface>>
interface Heater <<interface>>

class IOChannelThermometer 
class IOChannelHeater

Regulate -d-> "<<parameter>>" Thermometer
Regulate -d-> "<<parameter>>" Heater
Heater <|-d- IOChannelHeater
Thermometer <|-d- IOChannelThermometer
@enduml